### ISSUE TITLE
SQL Injection in delete.php

### ISSUE THREAD

**Issue by dotcarls** [tpageforfunzies/boulderphp#1]
Gotta clean _anything_ a user can feed into the system. In `delete.php`, the following is vulnerable:

```php
$ruRes = mysql_query("SELECT user FROM routes WHERE routeId=".$_GET['id']);
$ruRow = mysql_fetch_array($ruRes);
$userId = $ruRow['user'];
```

Because `$_GET['id']` isn't sanitized it's vulnerable to SQL injection. That injection could look something like a GET request to `<domain>/delete.php?id="1;DROP TABLE routes;"` (though that exact sting may not actually do it). 

Just a heads up :)

**Comment by tpageforfunzies** [comment]
Good looks man, that one slipped past me.  

Are my other methods of sanitizing sufficient?
For example the email input on the sign in page:
  `$email = trim($_POST['email']);`
  `$email = strip_tags($email);`
  `$email = htmlspecialchars($email);`

**Comment by dotcarls** [comment]
Pretty sure you could just do:

```php
$email = mysql_real_escape_string($_POST['email']);
```

But after looking at the docs, that function has been deprecated in recent PHP releases. 

I don't really do much with PHP anymore but I think the best practice is to use [PHP Data Objects](http://php.net/pdo) (PDO) + [Prepared Statements](http://php.net/manual/en/pdo.prepare.php). There's a module that's already done a ton of the hard work called `mysqli` that you should use. 

Basically, you write something like `$query = "SELECT * FROM routes WHERE id=?"` which is your ['prepared statement'](http://php.net/manual/en/mysqli.prepare.php). You can then [bind a variable](http://php.net/manual/en/mysqli-stmt.bind-param.php) like `$userId` to the statement which will cause the `?` to be replaced with the escaped value of `$userId` whenever the query is executed. You can do this with a bunch of `?`'s for more complex queries like `$query = "SELECT * FROM routes WHERE id=? AND status IN (?, ?, ?)"`, etc.

The end result is code that looks like:

```php
// open db connection
$connection = mysqli_connect("localhost", "root", "root", "boulder");

// prepared statement
if ($stmt = mysqli_prepare($connection, "SELECT user FROM routes WHERE routeId=?")) {
    // unescaped variable
    $routeId = $_GET['id'];
    
    // bind variables to ?'s
    mysqli_stmt_bind_param($stmt, "i", $routeId); // "i" for integer

    // ?'s now replaced with escaped $routeId
    mysqli_stmt_execute($stmt);

    // bind $userId to result
    mysqli_stmt_bind_result($stmt, $userId);

    // grab escaped result, store in $userId
    mysqli_stmt_fetch($stmt);
    
    // do werk
    if ($id == $userId) {
        // ...
    }

    // cleanup db connection
    mysqli_stmt_close($stmt);
}
```

You could write reusable functions to make this easier, essentially making an API

**Comment by tpageforfunzies** [comment]
Yeah I noticed that after I had already done all the calls in the deprecated mysql lol but the plan is to re do it all with mysqli and continue building the api out like I did for the delete function.  Appreciate you looking at it though man, feel free to play around with any of it if you get bored.

**Comment by tpageforfunzies** [comment]
Got all of the DB calls switched to mysqli and got the injection covered with a simple escape string, will look into the binding later

**Comment by dotcarls** [comment]
🙌 v nice!

The prepared statements / binding stuff is really useful. As mentioned I don't do much in `PHP` anymore but I do work with `MySQL` via `node` a lot; the most popular module `node-mysql` follows the same prepared statement syntax such that variables are indicated in queries using `?`.

If I could offer once more suggestion it would be to get in the habit of referencing issues in the commits when you close them. You can actually close the whole ticket without ever opening your browser by formatting your commit message certain ways, see [this for more info](https://help.github.com/articles/closing-issues-via-commit-messages/).

I use something called [commitizen](https://github.com/commitizen/cz-cli) in my projects to make this easier, but it's more oriented toward `node` than `PHP`. Regardless, you can just do the following:

```shell
git add .
git commit -m "Fixes #1 update code to use mysqli driver"
```

GitHub will automagically add a comment on the referenced ticket number with a link to the commit which is super helpful as your commit / issue history grows.

Hope you don't mind me commenting / code-reviewing; trying to improve my comfort with GitHub so maybe I will open a PR at some point :)

**Comment by tpageforfunzies** [comment]
Absolutely man that's why I posted it, hopefully people like yourself can come teach me how to be a better programmer <3

**Comment by dotcarls** [comment]
Btw your checkin doesn't actually fix the issue 😅 

This is the vulnerable line:
```php
$ruRes = mysqli_query($link, "SELECT user FROM routes WHERE routeId=".$_GET['id']);
```

You added some extra escaping in the `if` statement of `delete.php` but the real issue is that `$ruRes` is going to execute a query on the _raw_ value of `$_GET['id']`. 

`$_GET['id']` needs to be escaped and not directly concatenated onto the query string:

```php
$routeId = mysqli_real_escape_string($link, $_GET['id']);
$ruRes = mysqli_query($link, "SELECT user FROM routes WHERE routeId=".$routeId);
```

:)

**Comment by tpageforfunzies** [comment]
Ahhhh, I see what you're saying.  Fixed and appreciate all the input man!  Glad we finally got to collaborate on something even if it's just you telling me where I missed up haha
